### PR TITLE
Adding ALB + Cognito example

### PR DESCRIPTION
**Pull request by andreaswittig**
Adding an example to showcase how to add an authentication layer to the ALB with the help of Cognito.

### CODE REVIEW

**Comment by michaelwittig** [comment]
test

**Comment by andreaswittig** [comment]
> test

I missed to add a test?

**Comment by andreaswittig** [comment]
test

**Review by michaelwittig — APPROVED** [review]

**Comment by michaelwittig** [comment]
@andreaswittig you might want to add your new example to the root README of the project.

**Comment by andreaswittig** [comment]
test

**Comment by andreaswittig** [comment]
test

**Comment by andreaswittig** [comment]
test

**Comment by andreaswittig** [comment]
test

**Comment by andreaswittig** [comment]
test

**Comment by andreaswittig** [comment]
test

**Pull request merged**
